/*
 * FlightIntel for Pilots
 *
 * Copyright 2025 Nadeem Hasan <nhasan@nadmm.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.nadmm.airports.utils

class AircraftTypeDesginators {
    companion object {
        val aircraftTypeDesignators: Map<String, String> = mapOf(
            "A002" to "IRKUT, A-002",
            "A1" to "Douglas, A-1 Skyraider",
            "A10*" to "Fairchild (1), A-10 Thunderbolt 2",
            "A109" to "Augusta, AW-109 Da Vinci",
            "A119" to "Augusta, A-119 Koala",
            "A122" to "AEROTEC (1), A-122 Uirapuru",
            "A124" to "Antonov, An-124 Ruslan",
            "A129" to "Augusta, A-129 Mangusta",
            "A139" to "Augusta, AW-139",
            "A140" to "Antonov, An-140",
            "A148" to "Antonov, An-148",
            "A149" to "Augusta, AW-149",
            "A158" to "Antonov, An-158",
            "A16" to "AVIADESIGN, A-16 Sport Falcon",
            "A169" to "AugustaWESTLAND, AW-169",
            "A178" to "Antonov, An-178",
            "A189" to "AugustaWESTLAND, AW-189",
            "A19" to "AEROPRACT, A-19",
            "A19N" to "Airbus, A-319neo",
            "A20" to "Douglas, A-20 Havoc",
            "A205" to "OSKBES-MAI, MAI-205",
            "A20J" to "Schleicher, ASW-20J",
            "A20N" to "Airbus, A-320neo",
            "A21" to "AEROPRACT, A-21 Solo",
            "A210" to "AQUILA, A-210",
            "A211" to "ALFA-M, A-211",
            "A21N" to "Airbus, A-321neo",
            "A22" to "SADLER, A-22 Piranha",
            "A223" to "OSKBES-MAI, MAI-223 Kityonok",
            "A225" to "Antonov, An-225 Mriya",
            "A23" to "AEROPRACT, A-23 Dragon",
            "A25" to "AEROPRACT, A-25 Breeze",
            "A251" to "AVIATIK-ALYANS, Aleks-251",
            "A27" to "AEROPRACT, A-27",
            "A270" to "AERO (2), Ae-270 Propjet",
            "A29" to "AVANTAGE, A-29",
            "A2RT" to "KAZAN, Ansat 2RT",
            "A3*" to "Douglas, A-3 Skywarrior",
            "A306" to "Airbus, A-300B4-600",
            "A30B" to "Airbus. A-300B2-200",
            "A31" to "AVANTAGE, A-31 Spectrum",
            "A310" to "Airbus, A-310",
            "A318" to "Airbus, A-318",
            "A319" to "Airbus, A-319",
            "A320" to "Airbus, A-320",
            "A321" to "Airbus, A-321",
            "A32E" to "Schleicher, ASG-32EL",
            "A32P" to "Schleicher, ASG-32Mi",
            "A33" to "AEROPRACT, A-33",
            "A332" to "Airbus, A-330-200",
            "A333" to "Airbus, A-330-300",
            "A337" to "Airbus, A-330-700 Beluga XL",
            "A338" to "Airbus, A-330-800",
            "A339" to "Airbus, A-330-900",
            "A33E" to "Schleicher, AS-33Me",
            "A33P" to "Schleicher, AS-33Es",
            "A342" to "Airbus, A-340-200",
            "A343" to "Airbus, A-340-300",
            "A345" to "Airbus, A-340-500",
            "A346" to "Airbus, A-340-600",
            "A34E" to "Schleicher, AS-34Me",
            "A35" to "AVANTAGE, A-35 Scanner",
            "A359" to "Airbus, A-350-900 XWB",
            "A35K" to "Airbus, A-350-1000 XWB",
            "A37*" to "Cessna, 318D Dragonfly",
            "A388" to "Airbus, A-380-800",
            "A3ST" to "Airbus, A-300ST Beluga",
            "A4*" to "Douglas, A-4 Skyhawk",
            "A400" to "Airbus, A-400M Atlas",
            "A411" to "OSKBES-MAI, MAI-411",
            "A5" to "ICON, A-5",
            "A50" to "BERIEV, A-50",
            "A500" to "ADAM (2), A-500",
            "A504" to "AVRO, 504",
            "A6" to "Grumman, A-6 Intruder",
            "A600" to "ROTORWAY, A-600 Talon",
            "A660" to "AYRES, S-2R-T660 Turbo Thrush",
            "A700" to "ADAM (2), A-700 AdamJet",
            "A743" to "Antonov, An-74-300",
            "A748" to "AIL, 748",
            "A890" to "AVIATIKA, MAI-890",
            "A9" to "AAMSA, A-9 Quail",
            "A900" to "AVIATIKA, MAI-900 Acrobat",
            "A910" to "AVIATIKA, MAI-910",
            "AA1" to "AMERICAN, AA-1 Tr2",
            "AA37" to "AEROPRACT, A-37",
            "AA5" to "AMERICAN, AA-5 Traveler",
            "AAT3" to "AERO (3), AT-3",
            "AAT4" to "AERO (3), AT-4",
            "AB11" to "AERO BOERO, AB-115",
            "AB15" to "AERO BOERO, AB-150",
            "AB18" to "AERO BOERO, AB-180",
            "AB95" to "AERO BOERO, AB-95",
            "AC10" to "FD-COMPOSITES, ArrowCopter",
            "AC11" to "COMMANDER, Commander 114",
            "AC31" to "AVICOPTER, AC-311",
            "AC33" to "AVICOPTER, AC-313",
            "AC4" to "LIGHT WING, AC-4",
            "AC50" to "AERO (1), Commander 500",
            "AC52" to "AERO (1), Commander 520",
            "AC56" to "AERO (1), Commander 560",
            "AC5A" to "NANJING, AC-500 Aircar",
            "AC5M" to "AVIASTROITEL, AC-5M",
            "AC68" to "AERO (1), Commander 680 Super",
            "AC6L" to "NORTH AMERICAN ROCKWELL, 680FL Grand Commander",
            "AC72" to "AERO (1), Commander 720 Alti Cruiser",
            "AC80" to "AERO COMMANDER, 680T Turbo Commander",
            "AC90" to "Gulfstream Aerospace, 690 Jetprop Commander 840",
            "AC95" to "Gulfstream Aerospace, 695 Jetprop Commander 1000",
            "ACAM" to "LEZA, Air Cam",
            "ACAR" to "AUSTER, J-5B Autocar",
            "ACED" to "POWELL, P-70 Acey Deucy",
            "ACR2" to "ACRO SPORT, Acro-Sport 2",
            "ACRD" to "AVIA (3), Accord",
            "ACRO" to "ACRO SPORT, Acro-Sport 1",
            "ACSR" to "VICTA, Aircruiser",
            "AD20" to "BEIJING KEYUAN, AD-200",
            "ADEL" to "USTINOV, Adel",
            "ADVE" to "AUSTER, J-5 Adventurer",
            "ADVN" to "ADVENTURE AIR, Adventurer",
            "AE45" to "AERO (2), 45",
            "AEA1" to "AMERICAN EAGLE, A-1",
            "AERK" to "Aeronica, CF Scout",
            "AEST" to "AEROSTAR (1), 600",
            "AFOX" to "HALLEY, Apollo Fox",
            "AG02" to "GATARD, AG-02 Poussin",
            "AG04" to "GATARD, AG-04 Pigeon",
            "AG1" to "HALLEY, Apollo AG-1 Gyro",
            "AG10" to "CAIGA, AG-100",
            "AG14" to "ANDERSON-GREENWOOD, 14",
            "AG60" to "CAIGA, AG-600 Kunlong",
            "AGSH" to "AERO GARE, Sea Hawker",
            "AI10" to "IKAR, Ai-10 Ikar",
            "AIGT" to "AUSTER, J-5F Aiglet Trainer",
            "AIRD" to "BEAGLE, A-109 Airedale",
            "AIRL" to "AERONIX, Airelle",
            "AJ27" to "COMAC, ARJ-21-700",
            "AJET*" to "AOI, Alpha Jet",
            "AKNC" to "BAYKAR, Bayraktar Akıncı",
            "AKOY" to "LISA, Akoya",
            "AKRO" to "STEPHENS, Akro",
            "ALBU" to "AVIATION DEVELOPMENT, Alaskan Bushmaster",
            "ALC1" to "ALTAIR COELHO, AC-11",
            "ALGR" to "FANTASY AIR, Allegro",
            "ALH" to "Hindustan, ALH Dhruv",
            "ALIG" to "ARION, LS-1 Lightning",
            "ALIZ" to "BREGUET, 1050 Alizé",
            "ALO2" to "Aerospatiale, SA-318 Alouette 2",
            "ALO3" to "Aerospatiale, SA-316 Alouette 3",
            "ALPI" to "AUSTER, J-5Q Alpine",
            "ALSL" to "AIRLONY, Skylane",
            "ALTO" to "DIRECT FLY, Alto",
            "AM3" to "AERFER-AERMACCHI, AM-3",
            "AMX*" to "AERITALIA, AMX Ghibli",
            "AN12" to "Antonov, An-12",
            "AN2" to "AICSA, An-2",
            "AN22" to "Antonov, An-22 Antheus",
            "AN24" to "Antonov, An-24",
            "AN26" to "Antonov, An-26",
            "AN28" to "Antonov, An-28",
            "AN3" to "Antonov, An-3",
            "AN30" to "Antonov, An-30",
            "AN32" to "Antonov, An-32",
            "AN38" to "Antonov, An-38",
            "AN70" to "Antonov, An-70",
            "AN72" to "Antonov, An-72",
            "AN8" to "Antonov, An-8",
            "ANDR" to "MILLIOUD, Andromède",
            "ANGL" to "ANGEL, 44 Angel",
            "ANKA" to "TAI, Anka",
            "ANSN" to "AVRO, 652 Anson",
            "ANST" to "KAZAN, Ansat",
            "AP20" to "Aeroprakt, A-20",
            "AP22" to "Aeroprakt, A-22",
            "AP24" to "Aeroprakt, A-24 Viking",
            "AP26" to "Aeroprakt, A-26 Twin Vista",
            "AP28" to "Aeroprakt, A-28 Victor",
            "AP32" to "Aeroprakt, A-32 Vixxen",
            "AP36" to "Aeroprakt, A-36 Vulcan",
            "APM2" to "ISSOIRE, APM-20 Lionceau",
            "APM3" to "ISSOIRE, APM-30 Lion",
            "APM4" to "ISSOIRE, APM-40 Simba",
            "APUP" to "AEROPUP, Aeropup",
            "AR1" to "SILVERLIGHT, AR-1 American Ranger 1",
            "AR11" to "Aeronica, 11 Chief",
            "AR15" to "Aeronica, 15 Sedan",
            "AR50" to "Aeronica, 50 Chief",
            "AR5T" to "Aeronica, 50 Tandem",
            "AR65" to "Aeronica, 65 Super Chief",
            "AR6T" to "Aeronica, 60 Tandem",
            "ARCE" to "SCHEMPP-HIRTH, Arcus E",
            "ARCP" to "SCHEMPP-HIRTH, Arcus M",
            "ARES*" to "RUTAN, 151 Ares",
            "ARV1" to "ARV, ARV-1 Super 2",
            "ARVA" to "IAI, 101 Arava",
            "ARWF" to "ARROW (1), F Sport",
            "AS02" to "FFA, AS-202-15 Bravo",
            "AS14" to "Schleicher, ASK-14",
            "AS16" to "Schleicher, ASK-16",
            "AS20" to "Schleicher, ASW-20TOP",
            "AS21" to "Schleicher, ASK-21Mi",
            "AS22" to "Schleicher, ASW-22BE",
            "AS24" to "Schleicher, ASW-24E",
            "AS25" to "BINDER (2), ASH-25EB",
            "AS26" to "Schleicher, ASH-26E",
            "AS28" to "Schleicher, ASW-28E",
            "AS29" to "Schleicher, ASG-29E",
            "AS2T" to "FFA, AS-202-32TP Turbine Bravo",
            "AS30" to "Schleicher, ASH-30Mi",
            "AS31" to "Schleicher, ASH-31Mi",
            "AS32" to "Aerospatiale, AS-332B Super Puma",
            "AS3B" to "Aerospatiale, AS-332L2 Super Puma Mk2",
            "AS50" to "Aerospatiale, AS-350 AStar",
            "AS55" to "Aerospatiale, AS-355 Ecureuil 2",
            "AS65" to "Aerospatiale, AS-365 Dauphin 2",
            "AS80" to "STARCK, AS-80 Holiday",
            "ASO4" to "ASSO AEREI, Asso 4 Whisky",
            "ASO5" to "ASSO AEREI, Asso 5 Champion",
            "ASOX" to "ASSO AEREI, Asso 10 Jewel",
            "ASTO" to "Tecnam, Astore",
            "ASTR" to "Gulfstream Aerospace, Gulfstream G100",
            "AT1" to "ANTONIEWSKI, AT-1",
            "AT2P" to "AIR TRACTOR, AT-250",
            "AT3*" to "AIDC, AT-3 Tzu-Chung",
            "AT3P" to "AIR TRACTOR, AT-300",
            "AT3T" to "AIR TRACTOR, AT-400",
            "AT43" to "ATR, ATR-42-300",
            "AT44" to "ATR, ATR-42-400",
            "AT45" to "ATR, ATR-42-500",
            "AT46" to "ATR, ATR-42-600",
            "AT5P" to "AIR TRACTOR, AT-501",
            "AT5T" to "AIR TRACTOR, AT-502",
            "AT6T" to "AIR TRACTOR, AT-602",
            "AT72" to "ATR, ATR-72-201",
            "AT73" to "ATR, ATR-72-211",
            "AT75" to "ATR, ATR-72-212A (500)",
            "AT76" to "ATR, ATR-72-212A (600)",
            "AT8T" to "AIR TRACTOR, AT-802",
            "ATAC" to "AIRCRAFT TECHNOLOGIES, Acro 1",
            "ATIS" to "AIRCRAFT TECHNOLOGIES, Atlantis",
            "ATL" to "ROBIN, ATL",
            "ATLA" to "BREGUET, 1150 Atlantic",
            "ATP" to "British Aerospace, ATP",
            "ATTL" to "EURONEF, ATTL-1",
            "AU11" to "BEAGLE-AUSTER, E-3 Auster AOP11",
            "AUJ2" to "AUSTER, J-2 Arrow",
            "AUJ4" to "AUSTER, J-4 Archer",
            "AURA" to "SUNWARD, SA60 Aurora",
            "AUS3" to "TAYLORCRAFT (2), Auster 3",
            "AUS4" to "TAYLORCRAFT (2), Auster 4",
            "AUS5" to "AUSTER, Auster 5",
            "AUS6" to "AUSTER, 6A",
            "AUS7" to "AUSTER, Auster T7",
            "AUS9" to "AUSTER, Auster AOP9",
            "AV68" to "ALPLA, AVO-68 Samburo",
            "AVAM" to "AVID, Avid Amphibian",
            "AVID" to "AIRDALE, Avid Flyer",
            "AVIN" to "AVRO, 594 Avian",
            "AVTR" to "AERO ADVENTURE, Aventura 2",
            "B06" to "Augusta, AB-206 JetRanger",
            "B06T" to "Bell, 206LT TwinRanger",
            "B1" to "ROCKWELL, B-1 Lancer",
            "B103" to "BERIEV, Be-103 Bekas",
            "B105" to "BOLKOW, BO-105",
            "B13" to "AKAFLIEG BERLIN, B-13",
            "B14A" to "BellANCA, 14 Cruisair",
            "B14B" to "DOWNER, 14 Bellanca 260",
            "B14C" to "BellANCA, 14 Bellanca 260A",
            "B150" to "WINNER, B-150",
            "B17" to "Boeing, B-17 Flying Fortress",
            "B18T" to "Beech, 18 (turbine)",
            "B190" to "Beech, 1900",
            "B2" to "Northrop, B-2 Spirit",
            "B209" to "BOLKOW, BO-209 Monsun",
            "B212" to "Augusta, AB-212",
            "B214" to "Bell, 214A Isfahan",
            "B222" to "Bell, 222",
            "B23" to "Douglas, B-23 Dragon",
            "B230" to "Bell, 230",
            "B23E" to "BRM AERO, Bristell B23 Energic",
            "B24" to "CONSOLIDATED, B-24 Liberator",
            "B25" to "NORTH AMERICAN, B-25 Mitchell",
            "B26" to "Douglas, A-26 Invader",
            "B26M" to "MARTIN, 179 Marauder",
            "B29" to "Boeing, B-29 Superfortress",
            "B305" to "BRANTLY, 305",
            "B350" to "Beech, 300 (B300) Super King Air 350",
            "B360" to "YAKOVLEV AIRCRAFT, Bear 360",
            "B36T" to "ALLISON, 36 Turbine Bonanza",
            "B37M" to "Boeing, 737 MAX 7",
            "B38M" to "Boeing, 737 MAX 8",
            "B39M" to "Boeing, 737 MAX 9",
            "B3XM" to "Boeing, 737 MAX 10",
            "B407" to "Bell, 407",
            "B412" to "Augusta, AB-412",
            "B427" to "Bell, 427",
            "B429" to "Bell, 429 GlobalRanger",
            "B430" to "Bell, 430",
            "B461" to "British Aerospace, BAe-146-100",
            "B462" to "British Aerospace, BAe-146-200",
            "B463" to "British Aerospace, BAe-146-300",
            "B47G" to "Augusta, AB-47G",
            "B47J" to "Augusta, AB-47J",
            "B47T" to "SOLOY, Bell 47",
            "B505" to "Bell, 505 Jet Ranger X",
            "B52" to "Boeing, B-52 Stratofortress",
            "B525" to "Bell, 525 Relentless",
            "B58T" to "Beech, 58P Pressurized Baron",
            "B60" to "BOISAVIA, B-60 Mercurey",
            "B609" to "AugustaWESTLAND, AW-609",
            "B60T" to "Beech, 60 Royal Turbine Duke",
            "B701" to "Boeing, 707-100",
            "B703" to "Boeing, 707-300",
            "B712" to "Boeing, 717-200",
            "B720" to "Boeing, 720",
            "B721" to "Boeing, 727-100",
            "B722" to "Boeing, 727-200",
            "B732" to "Boeing, 737-200",
            "B733" to "Boeing, 737-300",
            "B734" to "Boeing, 737-400",
            "B735" to "Boeing, 737-500",
            "B736" to "Boeing, 737-600",
            "B737" to "Boeing, 737-700",
            "B738" to "Boeing, 737-800",
            "B739" to "Boeing, 737-900",
            "B741" to "Boeing, 747-100",
            "B742" to "Boeing, 747-200",
            "B743" to "Boeing, 747-300",
            "B744" to "Boeing, 747-400",
            "B748" to "Boeing, 747-8",
            "B74R" to "Boeing, 747SR",
            "B74S" to "Boeing, 747SP",
            "B752" to "Boeing, 757-200",
            "B753" to "Boeing, 757-300",
            "B762" to "Boeing, 767-200",
            "B763" to "Boeing, 767-300",
            "B764" to "Boeing, 767-400",
            "B772" to "Boeing, 777-200",
            "B773" to "Boeing, 777-300",
            "B778" to "Boeing, 777-8",
            "B779" to "Boeing, 777-9",
            "B77L" to "Boeing, 777-200LR",
            "B77W" to "Boeing, 777-300ER",
            "B788" to "Boeing, 787-8 BBJ",
            "B789" to "Boeing, 787-9 BBJ",
            "B78X" to "Boeing, 787-10 Dreamliner",
            "BA11" to "BAC, 111 One-Eleven",
            "BABY" to "CANADIAN HOME ROTORS, Baby Belle",
            "BALL" to "Balloon",
            "BARC" to "BUETHE, Barracuda",
            "BASS" to "BEAGLE, B-206",
            "BBAT" to "BRADLEY, BA-100 Aerobat",
            "BBIR" to "HOVEY, Beta Bird",
            "BCA3" to "BUHL, CA-3 Sport Airsedan",
            "BCAT" to "Grumman, F8F Bearcat",
            "BCS1" to "Airbus, A-220-100",
            "BCS3" to "Airbus, A-220-300",
            "BD10*" to "BEDE, BD-10",
            "BD17" to "BEDE, BD-17 Nuggett",
            "BD4" to "BEDE, BD-4",
            "BD5" to "ALTURAIR, BD-5B Micro",
            "BD5J" to "ALTURAIR, BD-5J Micro",
            "BD5T" to "BD-MICRO, BD-5T Micro",
            "BDOG" to "BEAGLE, B-125 Bulldog",
            "BE10" to "Beech, 100 King Air",
            "BE12" to "BERIEV, Be-12 Tchaika",
            "BE17" to "Beech, 17 Staggerwing",
            "BE18" to "Beech, 18 (piston)",
            "BE19" to "Beech, 19 Musketeer Sport",
            "BE20" to "Beech, 1300 Commuter",
            "BE22" to "BeechCRAFT, 220 Denali",
            "BE23" to "Beech, 23 Musketeer",
            "BE24" to "Beech, 24 Musketeer Super",
            "BE30" to "Beech, 300 Super King Air",
            "BE32" to "BERIEV, Be-30",
            "BE33" to "Beech, 33 Bonanza",
            "BE35" to "Beech, 35 Bonanza",
            "BE36" to "Beech, 36 Bonanza 36",
            "BE40" to "Beech, 400 Beechjet",
            "BE4W" to "Beech, 400XPR Beechjet",
            "BE50" to "Beech, 50 Twin Bonanza",
            "BE55" to "Beech, 55 Baron",
            "BE56" to "Beech, 56 Turbo Baron",
            "BE58" to "Beech, 58 Baron",
            "BE60" to "Beech, 60 Duke",
            "BE65" to "Beech, 65 Queen Air",
            "BE70" to "Beech, 70 Queen Air",
            "BE76" to "Beech, 76 Duchess",
            "BE77" to "Beech, 77 Skipper",
            "BE80" to "Beech. 80 Queen Air",
            "BE88" to "Beech, 88 Queen Air",
            "BE95" to "Beech, 95 Travel Air",
            "BE99" to "Beech, 99 Airliner",
            "BE9L" to "Beech, 90 (A90) King Air",
            "BE9T" to "Beech, 90 (F90) King Air",
            "BEAR" to "AVIPRO, RB-4 Bearhawk",
            "BELF" to "SHORT, SC-5 Belfast",
            "BER2" to "BERIEV, Be-200 Altair",
            "BER4" to "BERIEV, A-40 Albatross",
            "BETA" to "ROLLASON, Beta",
            "BEVR" to "ASAP, Beaver",
            "BF19" to "PODESVA, Bf-109G-2",
            "BFIT" to "BRISTOL, F-2B Fighter",
            "BILO" to "PENA, Bilouis",
            "BIPL" to "EAA, Biplane",
            "BIRD" to "TAYLOR (3), TA-2 Bird",
            "BISC" to "BILSAM, Sky Cruiser",
            "BK17" to "CASA, BK-117",
            "BKUT" to "BERKUT, Berkut",
            "BL11" to "BLERIOT, 11",
            "BL17" to "ALEXANDRIA, 17 Super Viking",
            "BL19" to "AVIABellANCA, 19 Skyrocket",
            "BL8" to "AMERICAN CHAMPION, 8 Scout",
            "BLBU" to "AMEUR, Altania",
            "BLCF" to "Boeing, 747-400LCF Dreamlifter",
            "BLEN" to "BRISTOL, 149 Blenheim",
            "BLKS" to "AIRCRAFT SPRUCE, Baby Lakes",
            "BM6" to "MARANDA, BM-6 Lark",
            "BMAN" to "AAK, Bushman",
            "BN2P" to "AVIONS FAIREY, BN-2A Defender",
            "BN2T" to "BRITTEN-NORMAN, BN-2T Defender 4000",
            "BO40" to "Boeing, 40",
            "BOLT" to "STEEN, Skybolt",
            "BOOM" to "RUTAN, 202 Boomerang",
            "BPAT" to "R & B, Bearhawk Patrol",
            "BPUM" to "BDC AERO, Puma",
            "BR14" to "BREGUET, 14 Replica",
            "BR23" to "BRM AERO, Bristell B23",
            "BR54" to "BARNETT, BRC-540",
            "BR60" to "BRUMBY, 600",
            "BR61" to "BRUMBY, 610 Evolution",
            "BR8" to "BRM AERO, Bristell B8",
            "BRAV" to "Tecnam, P-2004 Bravo",
            "BRB2" to "BRANTLY, B-2",
            "BREZ" to "AEROSTYLE, Breezer",
            "BROU" to "MAX HOLSTE , MH-1521 Broussard",
            "BS60" to "Beech-SFERMA, 60 Marquis",
            "BSTP" to "Bell, 214ST SuperTransport",
            "BSWN" to "DRONAMICS, Black Swan",
            "BT36" to "Beech, A36TC Bonanza",
            "BT7*" to "Boeing, BTX-1",
            "BTB2" to "BAYKAR, Bayraktar TB-2",
            "BTB3" to "BAYKAR, Bayraktar TB-3",
            "BTUB" to "KIMBREL, Dormoy Bathtub",
            "BU20" to "AIRCRAFT HYDRO-FORMING, Bushmaster 2000",
            "BU31" to "AERO (2), C-104",
            "BU33" to "BITZ, Bü-133 Jungmeister",
            "BU81" to "BUCKER, Bü-181 Bestmann",
            "BUC*" to "Hawker SIDDELEY, Buccaneer",
            "BUCA" to "ADVANCED AEROMARINE, Mallard",
            "BUSH" to "RAINBOW SKYREACH, BushCat",
            "BW60" to "BLACKWING, BW-600",
            "BW6T" to "BLACKWING, BW-635",
            "BX2" to "BRANDLI, BX-2 Cherry",
            "C02T" to "AJI, Turbo Star 402",
            "C04T" to "Cessna, 404 (turbine)",
            "C06T" to "Cessna, 206 (turbine)",
            "C07T" to "Cessna, 207 (turbine)",
            "C1" to "KAWASAKI, C-1",
            "C101*" to "CASA, A-36 Halcón",
            "C10T" to "ADVANCED AIRCRAFT, Spirit 750",
            "C119" to "Fairchild (1), C-119 Flying Boxcar",
            "C120" to "Cessna, 120",
            "C123" to "Fairchild (1), C-123 Provider",
            "C130" to "LOCKHEED, 182 Hercules",
            "C135" to "Boeing, NC-13",
            "C140" to "Cessna, 140",
            "C14T" to "AJI, Turbo Star 414",
            "C15" to "McDonnell Douglas, YC-15",
            "C150" to "Aviones COLOMBIA, 150",
            "C152" to "Aviones COLOMBIA, 152",
            "C160" to "TRANSALL, C-160",
            "C162" to "Cessna, 162 Skycatcher",
            "C17" to "Boeing, C-17 Globemaster 3",
            "C170" to "Cessna, 170",
            "C172" to "Cessna, 172",
            "C175" to "Cessna, 175",
            "C177" to "Cessna, 177",
            "C180" to "Cessna, 180",
            "C182" to "Aviones COLOMBIA, 182",
            "C185" to "AVIATECH, Super Cyclone",
            "C188" to "Aviones COLOMBIA, 188",
            "C190" to "Cessna, 190",
            "C195" to "Cessna, 195",
            "C2" to "Grumman, C-2 Greyhound",
            "C205" to "Cessna, 205",
            "C206" to "Aviones COLOMBIA, 206",
            "C207" to "Cessna, 207 Skywagon 207",
            "C208" to "Cessna, 208 Caravan 1",
            "C210" to "Aviones COLOMBIA, 210",
            "C212" to "Airbus, C-212",
            "C21T" to "ADVANCED AIRCRAFT, Regent 1500",
            "C22J" to "CAPRONI VIZZOLA, C-22J Ventura",
            "C240" to "Cessna, Corvalis TTx",
            "C25A" to "Cessna, 525A Citation CJ2",
            "C25B" to "Cessna, 525B Citation CJ3",
            "C25C" to "Cessna, 525C Citation CJ4",
            "C25M" to "Cessna, 525 Citation M2",
            "C270" to "CAUDRON, C-270 Luciole",
            "C27J" to "ALENIA, C-27J Spartan",
            "C295" to "Airbus, C-295",
            "C303" to "Aviones COLOMBIA, T303",
            "C306" to "CEA-UFMG, CB-10 Triathlon",
            "C309" to "CEA-UFMG, CEA-309 Mehari",
            "C30J" to "Lockheed Martin, 382J Super Hercules",
            "C310" to "Aviones COLOMBIA, 310",
            "C311" to "CEA-UFMG, CEA-311 Anequim",
            "C320" to "Cessna, 320 Executive Skyknight",
            "C335" to "Cessna, 335",
            "C336" to "Cessna, 336 Skymaster",
            "C337" to "Aviones COLOMBIA, 337",
            "C340" to "Aviones COLOMBIA, 340",
            "C365" to "EKW, C-3605",
            "C402" to "Aviones COLOMBIA, 402",
            "C404" to "Cessna, 404 Titan",
            "C408" to "Cessna, 408 SkyCourier",
            "C411" to "Cessna, 411",
            "C414" to "Aviones COLOMBIA, 414",
            "C42" to "IKARUS, C-42",
            "C421" to "Cessna, 421",
            "C425" to "Cessna, 425 Conquest 1",
            "C441" to "Cessna, 441 Conquest",
            "C46" to "CURTISS, C-46 Commando",
            "C500" to "Cessna, 500 Citation",
            "C501" to "Cessna, 501 Citation 1SP",
            "C510" to "Cessna, 510 Citation Mustang",
            "C525" to "Cessna, 525 Citation CJ1",
            "C550" to "Cessna, 550 Citation 2",
            "C551" to "Cessna, 551 Citation 2SP",
            "C55B" to "Cessna, 550B Citation Bravo",
            "C560" to "Cessna, 560 Citation 5",
            "C56X" to "Cessna, 560XL Citation Ascend",
            "C5M" to "LOCKHEED, C-5 Super Galaxy",
            "C650" to "Cessna, 650 Citation 3",
            "C680" to "Cessna, 680 Citation Sovereign",
            "C68A" to "Cessna, 680A Citation Latitude",
            "C700" to "Cessna, 700 Citation Longitude",
            "C72R" to "Aviones COLOMBIA, 172RG",
            "C750" to "Cessna, 750 Citation 10",
            "C77R" to "Aviones COLOMBIA, 177RG",
            "C82" to "Fairchild (1), C-82 Packet",
            "C82R" to "Aviones COLOMBIA, R182",
            "C82S" to "Cessna, T182 Turbo Skylane",
            "C82T" to "Cessna, TR182 Turbo Skylane RG",
            "C919" to "COMAC, C-919",
            "C97" to "Boeing, C-97 Stratofreighter",
            "CA12" to "COMP AIR, CA-12 Comp Air 12",
            "CA19" to "COMMONWEALTH (1), CA-13 Boomerang",
            "CA1P" to "Aerocomp, CA-10 Comp Air 10",
            "CA1T" to "Aerocomp, CA-10T Comp Air 10T",
            "CA25" to "COMMONWEALTH (1), CA-25 Winjeel",
            "CA3" to "Aerocomp, CA-3 Comp Air 3",
            "CA4" to "Aerocomp, CA-4 Comp Air 4",
            "CA41" to "CORVUS, CA-41 Racer",
            "CA6" to "Aerocomp, CA-6 Comp Air 6",
            "CA61" to "CVJETKOVIC, CA-61 Mini Ace",
            "CA65" to "CVJETKOVIC, CA-65 Skyfly",
            "CA7P" to "Aerocomp, CA-7P Comp Air 7P",
            "CA7T" to "Aerocomp, CA-7SLX Comp Air 7SLX",
            "CA8" to "Aerocomp, CA-8 Comp Air 8",
            "CA9" to "COMP AIR, CA-9 Comp Air 9",
            "CABI" to "UNIVERSAL COMPOSITE, Carbon Bird",
            "CABN" to "PARAMOUNT, Cabinaire",
            "CAD2" to "CLASS, Bush Caddy R-120",
            "CAD4" to "CLASS, Bush Caddy L-160",
            "CAML" to "SOPWITH, Camel",
            "CAMP" to "GREGA, GN-1 Aircamper",
            "CAN4" to "CAMPANA, AN-4",
            "CAPL" to "CAPELLA, Capella",
            "CAR" to "AEROCAD, Aerocar",
            "CARV" to "AVIATION TRADERS, ATL-98 Carvair",
            "CASS" to "CASSUTT, Special",
            "CAT" to "Boeing Canada, Canso",
            "CAT1" to "CREATIVE FLIGHT, MPA Aerocat SR",
            "CAT2" to "CREATIVE FLIGHT, MPA Aerocat TR",
            "CAW" to "Cessna, AW",
            "CB1" to "HATZ, CB-1 Biplane",
            "CC11" to "CUB CRAFTERS, CC-11 Carbon Cub",
            "CC19" to "CUB CRAFTERS, CC-19 NXCub",
            "CD2" to "CLAUDIUS Dornier, CD-2 Seastar",
            "CDC6" to "Cessna, DC-6",
            "CDUS" to "AUTOGYRO, Calidus",
            "CDW1" to "CHILTON, DW-1",
            "CE15" to "Chernov, Che-15",
            "CE22" to "Chernov, Che-22 Corvette",
            "CE23" to "Chernov, Che-23",
            "CE25" to "Chernov, Che-25",
            "CE27" to "Chernov, Che-27",
            "CE43" to "CERVA, CE-43 Guepard",
            "CEGL" to "CELAIR, Eagle 300",
            "CEL5" to "OTTO, Celera 500L",
            "CELR" to "MIRAGE, Celerity",
            "CENT" to "FOUND, 100 Centennial",
            "CFRE" to "COLYAER, Freedom",
            "CG3" to "CAUDRON, G-3",
            "CGAN" to "COLYAER, Gannet",
            "CH1" to "AIDC, A-CH-1 Chung-Tsing",
            "CH10" to "Zenair, CH-100 Mono-Z",
            "CH12" to "CICARÉ, CH-12",
            "CH14" to "CICARÉ, CH-14 Aguilucho",
            "CH15" to "Zenair, CH-150 Acro-Z",
            "CH18" to "Zenair, CH-180 Super Acro-Z",
            "CH20" to "HEINTZ , CH-200 Zénith",
            "CH25" to "Zenair, CH-250 Zénith",
            "CH2T" to "AMD, CH-2000 Alarus",
            "CH3" to "CHRISLEA, CH-3 Skyjeep",
            "CH30" to "Zenair, CH-300 Tri-Z",
            "CH40" to "CHAMPION, 402 Lancer",
            "CH50" to "Zenair, CH-50 Mini Zénith",
            "CH60" to "AMD, CH-601 Zodiac",
            "CH62" to "Zenair, CH-620 Gemini",
            "CH64" to "Zenair, CH-640 Zodiac",
            "CH65" to "AMD, CH-650 Zodiac",
            "CH7" to "HELI-SPORT, CH-7 Kompress",
            "CH70" to "AEROBRAVO, Bravo",
            "CH75" to "AMD, CH-750 Cruzer",
            "CH7A" to "Aeronica, 7AC Champion",
            "CH7B" to "AMERICAN CHAMPION, 7GCAA Citabria Adventure",
            "CH80" to "CZAW, CH-801 Stol",
            "CHAN" to "CADCOR, Chanute",
            "CHCS" to "ALPAERO, Choucas",
            "CHGO" to "KOREAN AIR, CHK-91 Chang-Gong 91",
            "CHIC" to "PODESVA, Chico",
            "CHIF" to "PAWNEE, Chief",
            "CHIN" to "ASAP, Chinook",
            "CHIP" to "LEGER, Super-Chipmunk",
            "CHR1" to "ELMWOOD, CA-05 Christavia Mk1",
            "CHR4" to "ELMWOOD, CH-8 Christavia Mk4",
            "CHSY" to "CHAYAIR, Sycamore",
            "CICA" to "HYDROPLANE, Cicada",
            "CJ1" to "CORBY, CJ-1 Starlet",
            "CJ6" to "HONGDU, BT-6",
            "CKUO*" to "AIDC, F-CK-1 Ching-Kuo",
            "CL2P" to "Canadair, CL-215",
            "CL2T" to "Canadair, CL-215T",
            "CL30" to "Bombardier, BD-100 Challenger 300",
            "CL35" to "Bombardier, BD-100 Challenger 350",
            "CL41*" to "Canadair, CL-41 Tutor",
            "CL4G" to "Canadair, CL-44-O Guppy",
            "CL60" to "Bombardier, CL-600 Challenger 650",
            "CLA" to "CALLAIR, A-2",
            "CLB1" to "AERO COMMANDER, B-1 Ag Commander",
            "CLBR" to "FISHER, Celebrity",
            "CLD2" to "ROTORTEC, Cloud Dancer 2",
            "CLDS" to "REARWIN, 8090 Cloudster",
            "CLON" to "AUTOGYRO, Cavalon",
            "CMA3" to "COLYAER, Martin 3",
            "CMAS" to "Cessna, C-145 Airmaster",
            "CMD1" to "AIR COMMAND, Commander 147",
            "CMDE" to "AIR COMMAND, Commander Elite Side-by-Side",
            "CMDT" to "AIR COMMAND, Commander Elite Tandem",
            "CN12" to "CIRCA, Nieuport 12-7/8",
            "CN35" to "Airbus, CN-235",
            "CNBR*" to "BAC, Canberra",
            "CNDR" to "GENERAL AVIA, F-20TP Condor",
            "CNGP" to "Cessna, NGP",
            "CNUK" to "Fleet, 80 Canuck",
            "CO50" to "COBALT, Co-50 Valkyrie",
            "COAR" to "COBRA, Arrow",
            "COBR" to "DEBORDE-ROLLAND, Cobra",
            "COL3" to "Cessna, 350",
            "COL4" to "Cessna, 400",
            "COLT" to "TEXAS AIRCRAFT, Colt",
            "COMU" to "HELICOM, H-1 Commuter",
            "CONI" to "LOCKHEED, C-121 Constellation",
            "COOT" to "AEROCAD, Coot",
            "CORO" to "CORVUS, CA-21 Phantom",
            "CORR" to "SIVEL, SD-27 Corriedale",
            "CORS" to "CHANCE VOUGHT, AU Corsair",
            "CORV" to "WOLFSBERG, Corvus",
            "COUG" to "ACRO SPORT, Cougar",
            "COUR" to "HELIO, H-250 Courier 2",
            "COY2" to "RAND, S-6 Coyote 2",
            "COZJ" to "CO-Z, CozyJet",
            "COZY" to "AEROCAD, AeroCanard",
            "CP10" to "Akrotech EUROPE, CAP-10",
            "CP13" to "CAARP, CP-1310 Super Emeraude",
            "CP20" to "CAARP, CAP-20",
            "CP21" to "MUDRY, CAP-21",
            "CP22" to "Akrotech EUROPE, CAP-222",
            "CP23" to "Akrotech EUROPE, CAP-232",
            "CP30" to "BINDER (1), CP-301 Smaragd",
            "CP32" to "ERPALS, CP-320 Super Emeraude",
            "CP60" to "PIEL, CP-60 Diamant",
            "CP65" to "PORTERFIELD, CP-65 Collegiate",
            "CP75" to "PIEL, CP-70 Béryl",
            "CP80" to "PIEL, CP-80 Zéphir",
            "CP90" to "PIEL, CP-90 Pinocchio 2",
            "CPNA" to "PENA, Capena",
            "CPUP" to "CULP, Sopwith Pup",
            "CR10" to "DYN'AERO, CR-100",
            "CRAC" to "PLUMB, CJ-3 Cracker Jack",
            "CRBN" to "CURTISS, 50 Robin",
            "CRER" to "RANS, S-7 Courier",
            "CRES" to "NEW ZEALAND, Cresco",
            "CRIO" to "MICROLEVE, Corsario",
            "CRJ1" to "Canadair, CL-600 Regional Jet CRJ-100",
            "CRJ2" to "Canadair, CL-600 Challenger 800",
            "CRJ7" to "Bombardier, CL-600 Regional Jet CRJ-550",
            "CRJ9" to "Canadair, CL-600 Challenger 890",
            "CRJX" to "Bombardier, CL-600 Regional Jet CRJ-1000",
            "CRUZ" to "CAG (2), PS-28 Cruiser",
            "CT4" to "AESL, CT-4 Airtrainer",
            "CTAH" to "RAINBOW, Cheetah",
            "CTLN" to "FLY SYNTHESIS, Catalina",
            "CUB2" to "ACES HIGH, Cuby 2",
            "CUCA" to "CULVER, LAR Cadet",
            "CULP" to "CULP, Special",
            "CULV" to "CULVER, V",
            "CULX" to "FISHER AERO, Culex",
            "CVLP" to "Convair, C-131",
            "CVLT" to "Canadair, CC-109 Cosmopolitan",
            "CX5" to "THATCHER, CX-5",
            "CYCL" to "CARLSON, Skycycle",
            "CYGT" to "Hawker, Cygnet",
            "D1" to "DERRINGER, New Derringer",
            "D11" to "AERO-DIFUSION, D-112 Popuplane",
            "D139" to "DORNA, D-139 Blue Bird",
            "D140" to "JODEL, D-140 Abeille",
            "D150" to "JODEL, D-150 Mascaret",
            "D18" to "JODEL, D-18",
            "D201" to "D'APUZZO, D-201 Sportwing",
            "D21" to "Fokker, D-21 Replica",
            "D228" to "Dornier, 228",
            "D25" to "NEW STANDARD, D-25",
            "D250" to "CENTRE EST, DR-200",
            "D253" to "CENTRE EST, DR-253 Regent",
            "D28D" to "Dornier, 128-2 Skyservant",
            "D28T" to "Dornier, 128-6 Turbo Skyservant",
            "D31" to "DRUINE, D-31 Turbulent",
            "D328" to "Dornier, 328",
            "D39" to "AKAFLIEG DARMSTADT, D-39",
            "D4" to "AUSTER, D-4",
            "D5" to "AUSTER, D-5",
            "D5TU" to "DRUINE, D-5 Turbi",
            "D6" to "AUSTER, D-6",
            "D6CR" to "DRUINE, D-60 Condor",
            "D7" to "Fokker, D-7 Replica",
            "D8" to "Fokker, D-8 Replica",
            "DA2" to "DAVIS, DA-2",
            "DA36" to "Diamond, DA-36 E-Star",
            "DA40" to "Diamond, DA-40 Club Star",
            "DA42" to "Diamond, DA-42 Guardian",
            "DA5" to "DAVIS, DA-5",
            "DA50" to "Diamond, DA-50 Magnum",
            "DA62" to "Diamond, DA-62",
            "DAHU" to "PENA, Dahu",
            "DAKH" to "FISHER, Dakota Hawk",
            "DAL1" to "SPEZIO, DAL-1 Tuholer",
            "DAL4" to "DALLACH, D-4 Fascination",
            "DAL5" to "DALLACH, D-5 Evolution",
            "DART" to "PARRISH, Dart",
            "DC10" to "Boeing, MD-10",
            "DC2" to "Douglas, DC-2",
            "DC3" to "Douglas, AC-47 Skytrain",
            "DC3S" to "Douglas, C-117D",
            "DC3T" to "BASLER, BT-67 Turbo 67",
            "DC4" to "Douglas, C-54 Skymaster",
            "DC6" to "Douglas, C-118 Liftmaster",
            "DC7" to "Douglas, DC-7",
            "DC85" to "Douglas, DC-8-50",
            "DC86" to "Douglas, DC-8-60",
            "DC87" to "Douglas, DC-8-70",
            "DC91" to "Douglas, DC-9-10",
            "DC92" to "Douglas, DC-9-20",
            "DC93" to "Douglas, DC-9-30",
            "DC94" to "Douglas, DC-9-40",
            "DC95" to "Douglas, DC-9-50",
            "DEAG" to "AMAX, Double Eagle",
            "DEFI" to "RUTAN, 40 Defiant",
            "DELF" to "LYAVIN, Delfin",
            "DFL6" to "DAMOURE-FABRE, DFL-6 Saphir",
            "DFLY" to "SLIPSTREAM, Dragonfly",
            "DG15" to "HOWARD (1), DGA-15",
            "DG1T" to "DG FLUGZEUGBAU, DG-1000M",
            "DG40" to "GLASER-DIRKS, DG-400",
            "DG50" to "GLASER-DIRKS, DG-500M",
            "DG60" to "GLASER-DIRKS, DG-600M",
            "DG80" to "DG FLUGZEUGBAU, DG-800",
            "DH2T" to "De Havilland Canada, DHC-2 Mk3 Turbo Beaver",
            "DH3T" to "De Havilland Canada, DHC-3 Turbo Otter",
            "DH4T" to "De Havilland Canada, DHC-4 Turbo Caribou",
            "DH60" to "De Havilland, DH-60 Moth",
            "DH80" to "De Havilland, DH-80 Puss Moth",
            "DH82" to "De Havilland, DH-82 Queen Bee",
            "DH83" to "De Havilland, DH-83 Fox Moth",
            "DH84" to "De Havilland, DH-84 Dragon",
            "DH85" to "De Havilland, DH-85 Leopard Moth",
            "DH87" to "De Havilland, DH-87 Hornet Moth",
            "DH88" to "De Havilland, DH-88 Comet Replica",
            "DH89" to "De Havilland, DH-89 Dragon Rapide",
            "DH8A" to "Bombardier, DHC-8-100 Dash 8",
            "DH8B" to "Bombardier, DHC-8-200 Dash 8",
            "DH8C" to "Bombardier, DHC-8-300 Dash 8",
            "DH8D" to "Bombardier, DHC-8-400 Dash 8",
            "DH90" to "De Havilland, DH-90 Dragonfly",
            "DH94" to "De Havilland, DH-94 Moth Minor",
            "DHA3" to "De Havilland AUSTRALIA, DHA-3 Drover",
            "DHC1" to "De Havilland, DHC-1 Chipmunk",
            "DHC2" to "AIRTECH (1), DHC-2-PZL3S Beaver",
            "DHC3" to "AIRTECH (1), DHC-3-1000 Otter",
            "DHC4" to "De Havilland Canada, C-7 Caribou",
            "DHC5" to "De Havilland Canada, C-115 Buffalo",
            "DHC6" to "De Havilland Canada, CC-138 Twin Otter",
            "DHC7" to "De Havilland Canada, DHC-7 Dash 7",
            "DIES" to "PENNEC-LUCAS, Dieselis",
            "DIJ3" to "DIJKMAN-DULKES, Dijkhastar 3",
            "DIJ4" to "DIJKMAN-DULKES, Dijkhastar 4",
            "DIMO" to "Diamond, HK-36 Eco Dimona",
            "DIPR" to "COLLINS, Dipper",
            "DISC" to "SCHEMPP-HIRTH, Discus 2CT",
            "DJET" to "Diamond, DJ-1 D-Jet",
            "DJIN" to "SUD, SO-1221 Djinn",
            "DLH2" to "LANGE, E-1 Antares DLR-H2",
            "DNGO" to "AERORIC, Dingo",
            "DO27" to "CASA, C-127",
            "DO28" to "Dornier, Do-28A",
            "DOCX" to "KOVACH-ELMENDORF, ES-3 Doc's RX",
            "DON" to "UNIKOMTRANSO, Don",
            "DOVE" to "De Havilland, DH-104 Devon",
            "DR1" to "Fokker, Dr-1 Replica",
            "DR10" to "CENTRE EST, DR-100 Ambassadeur",
            "DR22" to "CENTRE EST, DR-220 2+2",
            "DR30" to "CENTRE EST, DR-315 Petit Prince",
            "DR40" to "ROBIN, DR-400 2+2",
            "DRAG" to "CRAE, Dragon Fly",
            "DRIF" to "AUSTFLIGHT, Drifter",
            "DRTG" to "APPLEGATE & WEYANT, Dart GC",
            "DSA1" to "SMITH (1), DSA-1 Miniplane",
            "DSK" to "KILLINGSWORTH, DSK-1 Hawk",
            "DSLK" to "DRIGGS, Skylark",
            "DT45" to "CETC, TA-20",
            "DTA1" to "VERHEES, D-1 Delta",
            "DTA2" to "VERHEES, D-2 Delta",
            "DUB2" to "DUBNA, 2 Osa",
            "DUCE" to "BAKENG, Duce",
            "DUOD" to "SCHEMPP-HIRTH, Duo Discus T",
            "DUR5" to "DURAND, Mk5",
            "DV1" to "DOVA, DV-1 Skylark",
            "DV2" to "DOVA, DV-2 Infinity",
            "DV20" to "Diamond, DA-20 Eclipse",
            "DW1" to "BellANCA, DW-1 Eagle",
            "DWD2" to "DEWOITINE, D-26",
            "DYH2" to "DYNALI, H-2",
            "DYH3" to "DYNALI, H-3 EasyFlyer",
            "E110" to "Embraer, C-95 Bandeirante",
            "E120" to "Embraer, EMB-120 Brasilia",
            "E121" to "Embraer, EC-9 Xingu",
            "E135" to "Embraer, EMB-135ER",
            "E145" to "Embraer, C-99",
            "E170" to "Embraer, 170",
            "E190" to "Embraer, 190",
            "E195" to "Embraer, 195",
            "E2" to "Grumman, E-2 Daya",
            "E200" to "Extra, EA-200",
            "E230" to "Extra, EA-230",
            "E275" to "Embraer, ERJ-190-500",
            "E290" to "Embraer, E190-E2",
            "E295" to "Embraer, E195-E2",
            "E29E" to "BINDER (2), EB-29DE",
            "E2CB" to "TAYLOR (1), E-2 Cub",
            "E300" to "Extra, EA-300",
            "E314" to "Embraer, A-29",
            "E350" to "Cessna, E350",
            "E35L" to "Embraer, EMB-135BJ Legacy",
            "E390" to "Embraer, C-390 Millennium",
            "E3CF" to "Boeing, E-3A (CFM56) Sentry",
            "E3TF" to "Boeing, E-3A (TF33) Sentry",
            "E400" to "Extra, EA-400",
            "E45X" to "Embraer, EMB-145XR",
            "E500" to "Extra, EA-500",
            "E50P" to "Embraer, EMB-500 Phenom 100",
            "E530*" to "Cessna, E530 Scorpion",
            "E545" to "Embraer, EMB-545 Legacy 450",
            "E550" to "Embraer, EMB-550 Legacy 500",
            "E55P" to "Embraer, EMB-505 Phenom 300",
            "E6" to "Boeing, E-6 Mercury",
            "E737" to "Boeing, 737-700 AEWC",
            "E75L" to "Embraer, 175 (long wing)",
            "E75S" to "Embraer, 175 (short wing)",
            "E767" to "Boeing, E-767",
            "E7BH" to "E-7 GROUP, E-7 Bush Hog",
            "EA40" to "ECLIPSE, Eclipse 400",
            "EA50" to "ECLIPSE, Eclipse 500",
            "EAEA" to "GROSSO, Easy Eagle",
            "EAGL" to "AVIAT, Eagle",
            "EAGT" to "AMEAGLE, American Eaglet",
            "EAGX" to "CTRM, Eagle 150",
            "EB29" to "BINDER (2), EB-29",
            "EBOY" to "FMA, 20 El Boyero",
            "EC20" to "Airbus HELICOPTERS, EC-120 Colibri",
            "EC25" to "Airbus HELICOPTERS, EC-225 Super Puma Mk2+",
            "EC30" to "Airbus HELICOPTERS, EC-130",
            "EC35" to "Airbus HELICOPTERS, EC-135",
            "EC45" to "Airbus HELICOPTERS-KAWASAKI, BK-117C-2",
            "EC55" to "Airbus HELICOPTERS, EC-155",
            "EC6" to "CROSES, EC-6 Criquet",
            "EC75" to "Airbus HELICOPTERS-HARBIN, EC-175",
            "ECHO" to "Tecnam, P-92 Eaglet",
            "EDGE" to "ZIVKO, Edge 540",
            "EDGT" to "ZIVKO, Edge 540 T",
            "EF2" to "BYE Aerospace, eFlyer 2",
            "EFAN" to "Airbus, E-Fan",
            "EFOX" to "AEROPRO, Eurofox",
            "EFUS" to "MAGNUS, MG-11 eFusion",
            "EGL3" to "ROTORWAY, Eagle 300T",
            "EGRT" to "Grob, D-500 Egrett 2",
            "EH10" to "AugustaWESTLAND, AW-101",
            "EL10" to "ELA AVIACION, ELA-10 Eclipse",
            "EL20" to "ELITAR, IE-202",
            "ELA7" to "ELA AVIACION, ELA-07",
            "ELF" to "PARNALL, Elf",
            "ELIT" to "AIR, Epic Elite",
            "ELPS" to "EXPLORER (1), Ellipse",
            "ELSP" to "A2 CZ, Ellipse Spirit",
            "ELST" to "PUTZER, Elster",
            "ELTO" to "CONTINENTAL COPTERS, El Tomcat",
            "ELTR" to "ELITAR, IE-101 Elitar",
            "EM10" to "MARGANSKI, EM-10 Bielik",
            "EM11" to "MARGANSKI, EM-11 Orka",
            "EN28" to "Enstrom, 280 Shark",
            "EN48" to "Enstrom, 480",
            "EP9" to "EDGAR PERCIVAL, EP-9",
            "EPER" to "EPERVIER (1), Epervier",
            "EPIC" to "AIR, Epic Dynasty",
            "EPX1" to "EPERVIER (2), X-1",
            "ERAC" to "DICKEY, E-Racer",
            "ERCO" to "AIR PRODUCTS, F-1 Aircoupe",
            "ES11" to "ALPI, AH-130 Syton",
            "ES13" to "CLIFFORD AEROWORKS, Spad 13 80%",
            "ESCA" to "AIR, Epic Escape",
            "ESCP" to "JUST, Escapade",
            "ESQL" to "MOURA, Esqualo",
            "ETA" to "BINDER (2), Eta",
            "ETAR*" to "Dassault, Etendard 4",
            "EUFI*" to "ALENIA, Eurofighter 2000",
            "EUPA" to "EUROPA, Europa",
            "EURT" to "FFT, Eurotrainer 2000",
            "EV55" to "Evektor, EV-55 Outback",
            "EV97" to "Evektor, EV-97 EuroStar",
            "EVAN" to "EVANGEL, 4500 Evangel",
            "EVIC" to "AIR, Epic Victory",
            "EVOP" to "Lancair, Evolution Piston",
            "EVOT" to "Lancair, Evolution Turbine",
            "EVSS" to "Evektor, SportStar",
            "EX5T" to "AEA, Explorer 500T",
            "EXEC" to "HUZHOU TAIXIANG, Exec",
            "EXEJ" to "ROTORWAY, JetExec",
            "EXNG" to "Extra, NG",
            "EXPL" to "Boeing, MD-902 Explorer",
            "EXPR" to "EXPRESS, 90",
            "EZFL" to "Aerocomp, E-Z Flyer",
            "EZFT" to "Blue Yonder, Twin E-Z Flyer",
            "EZHV" to "Blue Yonder, E-Z Harvard",
            "EZIK" to "ISTRA, Ezhik",
            "EZKC" to "Blue Yonder, E-Z King Cobra",
            "F1*" to "MITSUBISHI, F-1",
            "F100" to "Fokker, 100",
            "F104*" to "Canadair, CF-104 Starfighter",
            "F106*" to "Convair, QF-106 Delta Dart",
            "F117*" to "LOCKHEED, F-117 Night Hawk",
            "F13" to "JUNKERS, F-13 Replica",
            "F14*" to "Grumman, F-14 Tomcat",
            "F15*" to "Boeing, F-15 Eagle",
            "F156" to "FIESELER, Fi-156 Storch",
            "F16*" to "Fokker, F-16 Fighting Falcon",
            "F18H*" to "ASTA, AF-18 Hornet",
            "F18S*" to "Boeing, EA-18 Growler",
            "F1FV" to "AVION, F-1 Favorit",
            "F2*" to "MITSUBISHI, F-2",
            "F22*" to "Lockheed Martin, F-22 Raptor",
            "F260" to "AERMACCHI, F-260E",
            "F26T" to "AERMACCHI, SF-260T",
            "F27" to "Conair, F-27 Firefighter",
            "F28" to "Fokker, F-28 Fellowship",
            "F2TH" to "Dassault, Falcon 2000",
            "F30" to "GOLDEN AVIO, F-30 Brio",
            "F35*" to "Lockheed Martin, F-35A Lightning 2",
            "F3F" to "Grumman, F3F Replica",
            "F4*" to "IAI, F-4 Kurnass 2000",
            "F402" to "FALCON AIR, Falcon 402",
            "F406" to "Cessna, F406 Caravan 2",
            "F41E" to "AEROSAMARA, F-41 El'brus",
            "F421" to "FALCON AIR, Falcon 421",
            "F5*" to "AIDC, F-5 Chung-Cheng",
            "F50" to "Fokker, 50",
            "F5SA*" to "IRIAF, S-100 Saeghe",
            "F60" to "Fokker, 60",
            "F600" to "SIAI-MARCHETTI, SF-600 Canguro",
            "F70" to "Fokker, 70",
            "F8*" to "CHANCE VOUGHT, F8 Crusader",
            "F86*" to "Canadair, CL-13 Sabre",
            "F8L" to "AEROMERE, F-8L Falco",
            "F900" to "Dassault, Falcon 900",
            "F9F*" to "Grumman, F9F Panther",
            "FA01" to "FLÄMING AIR, FA-01 Saphir",
            "FA02" to "FLÄMING AIR, FA-02 Smaragd VLA",
            "FA03" to "FLÄMING AIR, FA-03 Smaragd TMG",
            "FA04" to "FLÄMING AIR, FA-04 Peregrine",
            "FA10" to "Dassault, Falcon 10",
            "FA11" to "Fairchild (2), F-11 Husky",
            "FA20" to "Dassault, Falcon 20",
            "FA24" to "Fairchild (1), F-24 Argus",
            "FA50" to "Dassault, Falcon 50",
            "FA62" to "Fairchild (1), M-62 Cornell",
            "FA6X" to "Dassault, Falcon 6X",
            "FA7X" to "Dassault, Falcon 7X",
            "FA8X" to "Dassault, Falcon 8X",
            "FAET" to "ATEC, 321 Faeta",
            "FALC" to "AMERICAN AIRCRAFT, Falcon XP",
            "FALM" to "MILES, M-3 Falcon Major",
            "FANL" to "RHEIN, FL-1 Fanliner",
            "FANT" to "RHEIN, Fantrainer",
            "FB1A" to "BOWERS, Fly Baby 1A",
            "FB1B" to "BOWERS, Fly Baby 1B",
            "FB5" to "EURO-FLY, FB-5 Star Light",
            "FBA2" to "FOUND, FBA-2",
            "FC1*" to "CHENGDU, FC-1 Xiaolong",
            "FD2E" to "Flight Design, F-2e",
            "FDCT" to "Flight Design, CT",
            "FDF2" to "Flight Design, F-2",
            "FDMC" to "Flight Design, MC",
            "FE51" to "FIGHTER ESCORT WINGS, P-51",
            "FEST" to "AEROSTAR (2), 01 Festival",
            "FFLY" to "FAIREY, Firefly",
            "FG01" to "FARIGOUX, FG-01 Origan",
            "FGT" to "MIDWEST AEROSPORT, Formula GT",
            "FH11" to "Fairchild (1), FH-1100",
            "FIBO" to "STARFIRE, Firebolt Convertible",
            "FIKD" to "FIKE, D",
            "FIKE" to "FIKE, E",
            "FINC" to "Fleet, 10",
            "FJ10" to "AEROSTAR (1), FJ-100",
            "FJR3" to "FAJR, F-3",
            "FK12" to "B & F TECHNIK, FK-12 Comet",
            "FK14" to "B & F TECHNIK, FK-14 Polaris",
            "FK9" to "B & F TECHNIK, FK-9",
            "FL3" to "AVIA (1), L-3 Aviastarlet",
            "FL53" to "Meteor, FL-53",
            "FL54" to "Meteor, FL-54",
            "FL55" to "Meteor, FL-55",
            "FLAM" to "Dassault, MD-311 Flamant",
            "FLCO" to "FINMECCANICA, Falco",
            "FLE2" to "Fleet, 2",
            "FLE7" to "Fleet, 7",
            "FLIZ" to "FLITZER, Z-1 Flitzer",
            "FLSH" to "EURO-FLY, Flash",
            "FLSS" to "FLYER, Flyer NG",
            "FM25" to "FLYING MACHINES, FM-250 Vampire",
            "FMGO" to "AAK, Flamingo",
            "FN33" to "NARDI, FN-333 Riviera",
            "FNKB" to "AKRON, Funk B",
            "FOOF" to "STEWART (2), JD-2 Foo Fighter",
            "FORT" to "Fleet, 60 Fort",
            "FOUG*" to "Aerospatiale, CM-170R Magister",
            "FOX" to "DENNEY, Kitfox",
            "FOXT" to "CITA, Gavilán",
            "FRBD" to "Northrop Grumman, H-03 Firebird",
            "FREE" to "CABRINHA, 423 Free Spirit",
            "FREL" to "Aerospatiale, SA-321 Super Frelon",
            "FRNT" to "SKY RAIDER, Frontier",
            "FRON" to "FRONTIER, Frontier MD-2",
            "FS51" to "FALCONAR, SAL P-51D Mustang",
            "FT30" to "NAI, FT-300",
            "FU24" to "AIR PARTS, Fletcher FU-24",
            "FURY" to "Hawker, Fury",
            "FUSI" to "CORVUS, CH-11 Fusion",
            "FW02" to "FLYWALE, FW-02 Flywhale",
            "FW44" to "FMA, Fw-44 Stieglitz",
            "FW90" to "FLUG WERK, Fw-190 Replica",
            "FWSB" to "FleetWINGS, F-4 Sea Bird",
            "FX1" to "INNOVAVIATION, FX-1",
            "G1" to "G1 AVIATION, G-1",
            "G103" to "Grob, G-103C Twin 3SL",
            "G109" to "Grob, G-109",
            "G115" to "Grob, G-115",
            "G120" to "Grob, G-120",
            "G12T" to "Grob, G-120TP",
            "G140" to "Grob, G-140TP",
            "G150" to "Gulfstream Aerospace, Gulfstream G150",
            "G159" to "Grumman, G-159 Gulfstream 1",
            "G15T" to "Grob, G-115T Acro",
            "G160" to "Grob, G-160 Ranger",
            "G164" to "AERO MOD, G-164 Super Ag Max",
            "G180" to "GENERAL AIRCRAFT, G1-80 Skyfarer",
            "G200" to "Akrotech, G-200",
            "G202" to "Akrotech, G-202",
            "G21" to "Grumman, G-21A Goose",
            "G21M" to "McKinnon, G-21C Goose",
            "G21T" to "McKinnon, G-21E Turbo Goose",
            "G222" to "AERITALIA, G-222",
            "G250" to "Gulfstream Aerospace, Gulfstream G250",
            "G280" to "Gulfstream Aerospace, Gulfstream G280",
            "G2CA" to "GUIMBAL, G-2 Cabri",
            "G2GL*" to "SOKO, G-2 Galeb",
            "G2T1" to "GREAT LAKES, 2T-1 Sport",
            "G3" to "REMOS, G-3 Mirage",
            "G44" to "GANNET, G-44 Super Widgeon",
            "G46" to "FIAT, G-46",
            "G4SG*" to "SOKO, G-4 Super Galeb",
            "G59" to "FIAT, G-59",
            "G64T" to "AG-CAT, G-164 Super Turbine",
            "G70" to "GROPPO, G-70",
            "G73" to "Grumman, G-73 Mallard",
            "G73T" to "FRAKES, G-73T Turbo Mallard",
            "G800" to "AERODIS, G-802 Orion",
            "G91" to "FIAT, G-91R",
            "G96" to "Grumman, C-1 Trader",
            "G97" to "SAI (2), G-97 Spotter",
            "GA10" to "GIPPSAERO, GA-10",
            "GA20" to "GIPPSLAND, GA-200 Fatman",
            "GA4C" to "Gulfstream Aerospace, G-7 Gulfstream G400",
            "GA5C" to "Gulfstream Aerospace, G-7 Gulfstream G500",
            "GA6C" to "Gulfstream Aerospace, G-7 Gulfstream G600",
            "GA7" to "Grumman AMERICAN, GA-7 Cougar",
            "GA7C" to "Gulfstream Aerospace, G-8 Gulfstream G700",
            "GA8" to "GIPPSAERO, GA-8 Airvan",
            "GA8C" to "Gulfstream Aerospace, G-8 Gulfstream G800",
            "GABR" to "BLACKSHAPE, Bk-160 Gabriel",
            "GALX" to "Gulfstream Aerospace, Gulfstream G200",
            "GANT" to "FAIREY, Gannet",
            "GAUN" to "GLOSTER, Gauntlet",
            "GAVI" to "AERO MERCANTIL, 358 Gavilan",
            "GAZL" to "ABHCO, SA-342 Gazelle",
            "GB1" to "GAME COMPOSITES, GB-1 GameBird",
            "GBSP" to "BEETS, GB Special",
            "GC1" to "GLOBE, GC-1 Swift",
            "GDUK" to "ELLISON-MAHON, Gweduck",
            "GEMI" to "MILES, M-65 Gemini",
            "GENI" to "IFB, E-Genius",
            "GEPE" to "AERO SERVICES, Guêpe",
            "GF20" to "Grob, GF-200",
            "GJ11" to "HONGDU, GJ-11 Sharp Sword",
            "GL5T" to "Bombardier, BD-700 Global 5000",
            "GL7T" to "Bombardier, BD-700 Global 7000",
            "GLAD" to "GLOSTER, Gladiator",
            "GLAS" to "Glasair, Glasair",
            "GLEX" to "Bombardier, BD-700 Global 6000",
            "GLF2" to "Grumman, C-20J Gulfstream 2SP",
            "GLF3" to "Gulfstream Aerospace, C-20A Gulfstream 3",
            "GLF4" to "Gulfstream Aerospace, C-20F Gulfstream 4",
            "GLF5" to "Gulfstream Aerospace, C-37",
            "GLF6" to "Gulfstream Aerospace, G-6 Gulfstream G650",
            "GLID" to "Glider",
            "GLSP" to "NEW Glasair, Sportsman 2+2",
            "GLST" to "Glasair, GlaStar",
            "GLTU" to "STODDARD-HAMILTON, Turbine Glasair",
            "GM01" to "YALO, GM-01 Gniady",
            "GM17" to "INTRACOM, GM-17 Viper",
            "GMGC" to "IBIS (2), Grand Magic",
            "GNAT*" to "FOLLAND, Fo-144 Gnat",
            "GOBU" to "BUTTERFLY, Golden Butterfly",
            "GOLF" to "Tecnam, P-96 Golf",
            "GOOS" to "QUIKKIT, Glass Goose",
            "GOTR" to "GOAIR, GT-1 Trainer",
            "GP1" to "JIHLAVAN, Skyleader GP One",
            "GP3" to "OSPREY, GP-3 Osprey 2",
            "GP4" to "OSPREY, GP-4",
            "GPRO" to "GENEVATION, GenPro",
            "GR51" to "CAMERON, P-51G Grand 51",
            "GRFN" to "GRIFFON AERO, Griffon",
            "GRIF" to "Canada AIR RV, Griffin",
            "GRIZ" to "AEROTEK (3), Turbo Grizzly",
            "GSIS" to "INNOVATION, Genesis",
            "GSPN" to "Grob, G-180 SPn Utility Jet",
            "GUEP" to "AERO SERVICES, Guepard",
            "GURI" to "AEROMOT, AMT-600 Guri",
            "GX" to "REMOS, GX",
            "GY10" to "GARDAN, GY-100 Bagheera",
            "GY20" to "CAB, GY-20 Minicab",
            "GY30" to "CAB, GY-30 Supercab",
            "GY80" to "GARDAN, GY-80 Horizon",
            "GYRO" to "Ultralight gyroplane (autogyro, gyrocopter)",
            "H111" to "CASA, 2-111",
            "H12T" to "HILLER, UH-12E3T",
            "H160" to "Airbus HELICOPTERS, H-160",
            "H2" to "KAMAN, K-20 Seasprite",
            "H202" to "HB-AIRCRAFT, HB-202 Fledger",
            "H204" to "HB-FLUGTECHNIK, HB-204 Tornado",
            "H207" to "HB-FLUGTECHNIK, HB-207 Alfa",
            "H21" to "VERTOL, 42 Work Horse",
            "H25A" to "Hawker SIDDELEY, HS-125-1",
            "H25B" to "British Aerospace, BAe-125-700",
            "H25C" to "British Aerospace, BAe-125-1000",
            "H269" to "BREDANARDI, NH-300",
            "H40" to "HOFFMANN, H-40",
            "H43A" to "KAMAN, H-43A",
            "H43B" to "KAMAN, HH-43B Huskie",
            "H46" to "Boeing VERTOL, 107",
            "H47" to "AugustaWESTLAND, ICH-47 Chinook",
            "H500" to "Augusta, NH-500",
            "H53" to "Sikorsky, CH-53A Sea Stallion",
            "H53S" to "Sikorsky, CH-53E Super Stallion",
            "H60" to "ASTA, S-70 Seahawk",
            "H64" to "Boeing, AH-64 Longbow Apache",
            "HA2" to "HOLLMANN, HA-2 Sportster",
            "HA31" to "Hindustan, HA-31 Basant",
            "HA4T" to "Hawker BeechCRAFT, 4000 Hawker 4000",
            "HAHU" to "SINDLINGER, HH-1 Hawker Hurricane",
            "HAR*" to "ALENIA, AV-8 Harrier",
            "HAW*" to "BAE SYSTEMS, CT-155 Hawk",
            "HAW3" to "GROEN, H2X Hawk 3",
            "HAWK*" to "BAE SYSTEMS, CT-155 Hawk",
            "HB21" to "Brditschka, HB-21 Hobbylifter",
            "HB23" to "Brditschka, HB-23 Hobbyliner",
            "HB3" to "Brditschka, HB-3",
            "HCAT" to "Grumman, F6F Hellcat",
            "HD34" to "HUREL-DUBOIS , HD-34",
            "HDJT" to "HONDA, HA-420 HondaJet",
            "HEAD" to "STEWART (2), JD-1 Headwind",
            "HERN" to "De Havilland, DH-114 Heron",
            "HF20" to "HFB, HFB-320 Hansa",
            "HI27" to "HIRTH, Hi-27 Acrostar",
            "HIGH" to "JUST, JA20 Highlander",
            "HIND" to "Hawker, Hind",
            "HL2" to "LAMBACH, HL-2 Replica",
            "HLD4" to "HALBERSTADT, D-4 Replica",
            "HM38" to "FALCONAR, HM-380 Ladybug",
            "HN70" to "NICOLLIER, HN-700 Menestrel 2",
            "HORN" to "WALLERKOWSKI, Hornisse",
            "HORZ" to "FISHER, Horizon",
            "HPTR" to "IDEA, Hydropteron",
            "HR10" to "ROBIN, HR-100 President",
            "HR20" to "ROBIN, HR-200",
            "HRM9" to "ELBIT, Hermes 900",
            "HRNT" to "AAK, Hornet",
            "HRON" to "IAI, Harfang",
            "HSMT" to "ROTORSMART, HeliSmart",
            "HT16*" to "Hindustan, HJT-16 Kiran",
            "HT2" to "Hindustan, HT-2",
            "HT32" to "Hindustan, HPT-32 Deepak",
            "HT34" to "Hindustan, HTT-34",
            "HT36*" to "Hindustan, HJT-36 Sitara",
            "HT40" to "Hindustan, HTT-40",
            "HU1" to "Shenyang SAILPLANE, HU-1 Seagull",
            "HU2" to "Shenyang SAILPLANE, HU-2 Petrel",
            "HUCO" to "Bell, 209 HueyCobra",
            "HUML" to "HUMMEL, Hummel Bird",
            "HUMM" to "AEROTEK (2), Hummingbird",
            "HUNT*" to "Hawker, Hunter",
            "HURI" to "Hawker, Hurricane",
            "HURK" to "TAI, TT-32 Hürkuş",
            "HUSK" to "AVIAT, A-1 Husky",
            "HW4P" to "GROEN, Hawk 4",
            "HW4T" to "GROEN, Jet Hawk 4T",
            "HX2" to "HELOWERKS, HX-2 Wasp",
            "HYPR" to "P&M AVIATION, HypR",
            "I103" to "Ilyushin, Il-103",
            "I112" to "Ilyushin, Il-112",
            "I114" to "Ilyushin, Il-114",
            "I115" to "AISA, I-115",
            "I11B" to "AISA, I-11B Peque",
            "I153" to "Polikarpov, I-153",
            "I15B" to "Polikarpov, I-15bis",
            "I16" to "Polikarpov, I-16",
            "I22*" to "INSTYTUT LOTNICTWA, I-22 Iryda",
            "I23" to "INSTYTUT LOTNICTWA, I-23 Manager",
            "I3" to "INTERAVIA, I-3",
            "I66" to "IANNOTTA, I-66 San Francisco",
            "IA46" to "DINFIA, IA-46 Ranquel",
            "IA51" to "DINFIA, IA-51 Tehuelche",
            "IA58" to "FMA, IA-58 Pucará",
            "IA63*" to "FMA, AT-63 Pampa",
            "IFUR" to "ISAACS, Fury",
            "IL14" to "AVIA (2), Av-14",
            "IL18" to "Ilyushin, Il-18",
            "IL28" to "HARBIN, H-5",
            "IL38" to "Ilyushin, Il-38",
            "IL62" to "Ilyushin, Il-62",
            "IL76" to "Ilyushin, Il-76",
            "IL86" to "Ilyushin, Il-86",
            "IL96" to "Ilyushin, Il-96",
            "IMPU" to "IMPULSE, Impulse",
            "INCQ" to "INPAER, Conquest",
            "INEC" to "INPAER, Excel",
            "INEX" to "INPAER, Explorer",
            "INTG" to "AURA AERO, Integral R",
            "ION" to "ION, Ion",
            "IP06" to "IPE, IPE-06 Curucaca",
            "IP10" to "IPE, IPE-010",
            "IP26" to "IPAI, IPAI-26 Tuca",
            "IP6A" to "IPE, IPE-06A",
            "IPAN" to "Embraer, EMB-200 Ipanema",
            "IR21" to "ICA, IAR-821",
            "IR22" to "ICA, IAR-822",
            "IR23" to "ICA, IAR-823",
            "IR24" to "ICA, IAR-824",
            "IR25" to "ICA, IAR-825TP Triumf",
            "IR27" to "BUCURESTI, IAR-827 Dacic",
            "IR28" to "ICA, IAR-28MA",
            "IR31" to "ICA, IAR-831 Pelican",
            "IR46" to "IAR, IAR-46 Katty",
            "IR99*" to "AVIOANE, IAR-109 Swift",
            "IRBS" to "KUBICEK, M-4 Irbis",
            "IS2" to "INSTYTUT LOTNICTWA, IS-2",
            "IS28" to "IAR, IS-28M2",
            "ISAT" to "AEROJAMES, 01 Isatis",
            "ISPT" to "ISAACS, Spitfire",
            "J1" to "AUSTER, J-1 Aiglet",
            "J10*" to "CHENGDU, F-10",
            "J177" to "AERODYNOS, JA-177 Evolution",
            "J2" to "Piper, J-2 Cub",
            "J20*" to "CHENGDU, J-20",
            "J3" to "AMERICAN LEGEND, AL-3C Legend Cub",
            "J300" to "ALMS, J-300 Joker",
            "J328" to "328 SUPPORT SERVICES, Dornier 328JET",
            "J4" to "Piper, J-4 Cub Coupe",
            "J400" to "JIHLAVAN, JA-400 Skyleader 400",
            "J40E" to "ZALL JIHLAVAN, JA-400 Skyleader 400 Electric",
            "J4B2" to "BARNETT, J4B2",
            "J5" to "Piper, AE Cub Cruiser",
            "J600" to "ACS (2), JA-600 Skyleader 600",
            "J8A*" to "Shenyang, J-8A",
            "J8B*" to "Shenyang, F-8T",
            "JAB2" to "JABIRU, Jabiru J160",
            "JAB4" to "JABIRU, Jabiru J200",
            "JABI" to "JABIRU, Jabiru J120",
            "JACE" to "ACE, Junior Ace",
            "JAG2" to "JAG HELICOPTER, JAG",
            "JAGR*" to "Hindustan, Jaguar",
            "JAJ5" to "ALPHA, J-5 Marco",
            "JAJ6" to "J & AS, J-6 Fregata",
            "JANU" to "SCHEMPP-HIRTH, Janus BM",
            "JARO" to "JACKAROO, Thruxton Jackaroo",
            "JAST*" to "SOKO, IJ-21 Jastreb",
            "JB1" to "INDEPENDENT, X-JB-1 SeaDragon",
            "JB15" to "OBERLERCHNER, JOB-15",
            "JC01" to "COUPE, JC-01",
            "JC02" to "COUPE, JC-02",
            "JCOM" to "AERO COMMANDER, 1121 Jet Commander",
            "JCRU" to "AASI, Jetcruzer",
            "JD2" to "DYKE, JD-2 Delta",
            "JDOE" to "AMERICAN HOMEBUILTS, John Doe",
            "JE2" to "EICH, JE-2 Gyroplane",
            "JFOX" to "AIRO, 1",
            "JH7*" to "XIAN, FBC-1 Flying Leopard",
            "JK05" to "EKOLOT, JK-05 Beetle",
            "JL9*" to "GUIZHOU, FTC-2000 Shanying",
            "JN76" to "CAUDRON, CR-760 Cyclone Replica",
            "JPM1" to "MARIE, JPM-01 Medoc",
            "JPRO*" to "BAC, 145 Jet Provost",
            "JRO" to "DTA, J-RO",
            "JS1J" to "Jonker, JS-1 Revelation (jet)",
            "JS2J" to "Jonker, JS-2 Revenant (jet)",
            "JS2P" to "Jonker, JS-2 Revenant (piston)",
            "JS3" to "CENTURY, Jetstream 3",
            "JS31" to "British Aerospace, BAe-3100 Jetstream 31",
            "JS32" to "British Aerospace, BAe-3200 Jetstream Super 31",
            "JS3E" to "Jonker, JS-3 Rapture (electric)",
            "JS3J" to "Jonker, JS-3 Rapture (jet)",
            "JS41" to "AI(R), BAe-4100 Jetstream 41",
            "JSX" to "SONEX, JSX SubSonex",
            "JT2" to "TAYLOR (4), JT-2 Titch",
            "JU52" to "CASA, 352L",
            "JUN1" to "KAMINSKAS, RK-1 Jungster 1",
            "JUN2" to "KAMINSKAS, RK-2 Jungster 2",
            "JUNR" to "ANDREASSON, BA-7",
            "JUPI" to "LAMMER GEYER, Jupiter",
            "K100" to "DAHER, Kodiak 100",
            "K126" to "ICA, Ka-126",
            "K209" to "FAMA, K-209 KISS",
            "K226" to "KAMOV, Ka-226 Sergei",
            "K35E" to "Boeing, KC-135E Stratotanker",
            "K35R" to "Boeing, C-135FR Stratotanker",
            "K50*" to "KOREA Aerospace, A-50 Golden Eagle",
            "K51" to "KOVÁCS, K-51 Peregrino",
            "K8*" to "HONGDU, JL-8",
            "PA11" to "Piper, PA-11 Cub Special",
            "PA12" to "Piper, 12 Supercruiser",
            "PA16" to "Piper, PA-16 Clipper",
            "PA18" to "Piper, 18 Super Cub",
            "PA20" to "Piper, PA-20 Pacer",
            "PA22" to "Piper, 22 Tri-Pacer",
            "PA23" to "Piper, PA-23-150/160 Apache",
            "PA24" to "Piper, PA-24 Comanche",
            "PA25" to "Piper, PA-25 Pawnee",
            "PA27" to "Piper, Aztec",
            "PA28" to "Piper, PA-28 Cherokee",
            "P28A" to "Piper, PA-28 Cherokee",
            "P28B" to "Piper, PA-28 Cherokee",
            "P28R" to "Piper, PA-28 Arrow",
            "PA30" to "Piper, PA-30 Turbo Twin Comanche/Turbo Twin Comanche",
            "PA31" to "Piper, Navajo PA-31",
            "PA32" to "Piper, Cherokee Six",
            "PA34" to "Piper, PA-34 Seneca",
            "PA36" to "Piper, PA-36 Pawnee Brave",
            "PA38" to "Piper, Tomahawk PA38",
            "PA44" to "Piper, Seminole",
            "PA46" to "Piper, Malibu",
            "PAT4" to "Piper, PA-31T3-500 T-1040",
            "PAY1" to "Piper, Cheyenne 1",
            "PAY2" to "Piper, Cheyenne 2",
            "PAY3" to "Piper, PA-42-720 Cheyenne 3",
            "PAY4" to "Piper, Cheyenne 400",
            "PC12" to "Pilatus, PC-12",
            "PC24" to "Pilatus, PC-24",
            "PRM1" to "Raytheon, Premier 1/390 Premier 1",
            "R22" to "Robinson, R22",
            "R44" to "Robinson, R44",
            "R66" to "Robinson, R66",
            "R721" to "Boeing, 727-100RE Super 27",
            "R722" to "Boeing, 727-200RE Super 27",
            "RJ1H" to "Avro, RJ-100 Avroliner",
            "RJ85" to "Avro, RJ-85 Avroliner",
            "RV12" to "Van's, RV-12",
            "S108" to "Stinson, 108 Voyager",
            "S22T" to "Cirrus, SR-22 Turbo",
            "SB20" to "Saab, 2000",
            "SBR1" to "North American Rockwell Sabre, 40/60",
            "SBR2" to "North American Rockwell Sabre, 75",
            "SC7" to "Short, Skyvan SC7",
            "SF34" to "Saab, SF 340",
            "SF50" to "Cirrus, Vision SF50",
            "SH33" to "Shorts, 330",
            "SH36" to "Shorts, 360",
            "SR20" to "Cirrus, SR-20",
            "SR22" to "Cirrus, SR 22",
            "SU95" to "Sukhoi, Superjet 100-95",
            "SW3" to "Fairchild Swearingen, SA-226T/TB Merlin 3",
            "SW4" to "Swearingen, SA-227AT Merlin 4",
            "T210" to "Cessna, T210 Turbo Centurion",
            "T28" to "North American, T-28 Trojan",
            "T34P" to "Beech, T-34/45 Mentor",
            "T38" to "Northrop, T-38 Talon",
            "T6" to "North American, T-6 Texan",
            "TAYB" to "Taylorcraft, BC",
            "TB20" to "Socata, TB-20 Trinidad",
            "TBM7" to "Socata, TBM-700/700A",
            "TBM8" to "Socata, TBM-850",
            "TBM9" to "Socata, TBM-900",
            "TEX2" to "Raytheon Texan, 2",
            "TOBA" to "Socata, TB-10 Tobago",
            "V22" to "Bell, V-22 Osprey",
            "WW24" to "IAI, 1124 Westwind",
        )

        fun getAircraftName(designator: String): String {
            return aircraftTypeDesignators[designator] ?: ""
        }
    }
}