android.buildfeatures.buildconfig=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.useAndroidX=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2048M
org.gradle.warning.mode=all
android.r8.optimizedResourceShrinking=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.builtInKotlin=true
android.newDsl=true
