[versions]
preferenceKtx = "1.2.1"
activityKtx = "1.12.4"
fragmentKtx = "1.8.9"
viewpager2 = "1.1.0"
material = "1.13.0"
swiperefreshlayout = "1.2.0"
coordinatorlayout = "1.3.0"
drawerlayout = "1.2.0"
localbroadcastmanager = "1.1.0"
playServicesLocation = "21.3.0"
firebaseMessagingKtx = "24.1.2"
coreKtx = "1.17.0"
workRuntimeKtx = "2.11.1"
kotlinxCoroutines = "1.10.2"
kotlinxSerializationJson = "1.10.0"
gson = "2.13.2"
desugarJdkLibs = "2.1.5"

[libraries]
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

[plugins]
