#!/bin/bash

#/*
# * FlightIntel for Pilots
# *
# * Copyright 2019 Nadeem Hasan <nhasan@nadmm.com>
# *
# * This program is free software: you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation, either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program.  If not, see <http://www.gnu.org/licenses/>.
# */

DATA_CYCLE="190425";

FADDS_CYCLE="2019-04-25";
DTPP_CYCLE="190425";
DCS_CYCLE="20190425";
DOF_CYCLE="190425";

DATA_DIR="data";
if [ ! -d "${DATA_DIR}" ]; then
    mkdir -p ${DATA_DIR};
fi

OUT_DIR="${DATA_DIR}/database";
if [ ! -d "${OUT_DIR}" ]; then
    mkdir -p ${OUT_DIR};
fi
GS_DATA_URL="gs://flightintel/database";

LIBRARY_DIR="${DATA_DIR}/library";
GS_LIBRARY_URL="gs://flightintel/library";

OUT_FILE="${OUT_DIR}/fadds_${DATA_CYCLE}.db";
if [ ! -f "${OUT_FILE}.gz" ]; then
    BASE_DIR="${DATA_DIR}/FADDS/${DATA_CYCLE}";
    if [ ! -d "${BASE_DIR}" ]; then
        mkdir -p ${BASE_DIR};
    fi
    FADDS_FILE="${BASE_DIR}/28DaySubscription_Effective_${FADDS_CYCLE}.zip";
    if [ ! -f "${FADDS_FILE}" ]; then
        FADDS_URL="https://nfdc.faa.gov/webContent/28DaySub/28DaySubscription_Effective_${FADDS_CYCLE}.zip";
        echo "Downloading FADDS ${FADDS_CYCLE} file:";
        wget -O ${FADDS_FILE} ${FADDS_URL};
        unzip -o -d ${BASE_DIR} ${FADDS_FILE};
    fi
    echo "Running load_fadds.pl ${BASE_DIR} ${OUT_FILE}:";
    ./load_fadds.pl ${BASE_DIR} ${OUT_FILE}
    echo "Running load_wx_stations.pl ${BASE_DIR} ${OUT_FILE}:";
    ./load_wx_stations.pl ${BASE_DIR} ${OUT_FILE}
    echo "Running load_atc_phones.pl ${OUT_FILE}:";
    ./load_atc_phones.pl ${OUT_FILE}
    echo "Running cached_tz_lookup.pl ${OUT_FILE} ${OUT_DIR}/fadds_prev.db";
    ./cached_tz_lookup.pl ${OUT_FILE} ${OUT_DIR}/fadds_prev.db;
    echo "Running geonames_tz_lookup.pl ${OUT_FILE}:";
    ./geonames_tz_lookup.pl ${OUT_FILE}
    echo "Making a copy of FADDS file:";
    cp ${OUT_FILE} ${OUT_DIR}/fadds_prev.db;
    gzip ${OUT_FILE};
    echo "--"
fi

OUT_FILE="${OUT_DIR}/dtpp_${DATA_CYCLE}.db";
if [ ! -f "${OUT_FILE}.gz" ]; then
    BASE_DIR="${DATA_DIR}/d-TPP/${DTPP_CYCLE}";
    if [ ! -d "${BASE_DIR}" ]; then
        mkdir -p ${BASE_DIR};
    fi
    DTPP_FILE="${BASE_DIR}/DDTPPE_${DTPP_CYCLE}.zip";
    if [ ! -f "${DTPP_FILE}" ]; then
        DTPP_URL="https://aeronav.faa.gov/upload_313-d/terminal/DDTPPE_${DTPP_CYCLE}.zip";
        echo "Downloading d-TPP ${DTPP_CYCLE} file:";
        wget -O ${DTPP_FILE} ${DTPP_URL};
        unzip -o -d ${BASE_DIR} ${DTPP_FILE} d-TPP_Metafile.xml;
    fi
    echo "Running load_dtpp_metadata.pl ${BASE_DIR} ${OUT_FILE}";
    ./load_dtpp_metadata.pl ${BASE_DIR} ${OUT_FILE};
    gzip ${OUT_FILE};
    echo "--";
fi

OUT_FILE="${OUT_DIR}/dcs_${DATA_CYCLE}.db";
if [ ! -f "${OUT_FILE}.gz" ]; then
    BASE_DIR="${DATA_DIR}/d-CS/${DCS_CYCLE}";
    if [ ! -d "${BASE_DIR}" ]; then
        mkdir -p ${BASE_DIR};
    fi
    DCS_FILE="${BASE_DIR}/DCS_${DCS_CYCLE}.zip";
    if [ ! -f "${DCS_FILE}" ]; then
        DCS_URL="https://aeronav.faa.gov/Upload_313-d/supplements/DCS_${DCS_CYCLE}.zip";
        echo "Downloading d-CS ${DCS_CYCLE} file:";
        wget -O ${DCS_FILE} ${DCS_URL};
	unzip -o -d ${BASE_DIR} ${DCS_FILE} afd_*.xml;
    fi
    echo "Running load_dafd_metadata.pl ${BASE_DIR} ${OUT_FILE}:";
    ./load_dafd_metadata.pl ${BASE_DIR} ${OUT_FILE};
    gzip ${OUT_FILE};
    echo "--";
fi

OUT_FILE="${OUT_DIR}/dof_${DATA_CYCLE}.db";
if [ ! -f "${OUT_FILE}.gz" ]; then
    BASE_DIR="${DATA_DIR}/DOF/${DOF_CYCLE}";
    if [ ! -d "${BASE_DIR}" ]; then
        mkdir -p ${BASE_DIR};
    fi
    DOF_FILE="${BASE_DIR}/DAILY_DOF_DAT.ZIP";
    if [ ! -f "${DOF_FILE}" ]; then
        DOF_URL="https://aeronav.faa.gov/Obst_Data/DAILY_DOF_DAT.ZIP"
        echo "Downloading DDOF file:";
        wget -O ${DOF_FILE} ${DOF_URL};
        unzip -o -d ${BASE_DIR} ${DOF_FILE};
    fi
    echo "Running load_dof.pl ${DATA_CYCLE}:";
    ./load_dof.pl ${BASE_DIR} ${OUT_FILE};
    gzip ${OUT_FILE};
    echo "--";
fi

OUT_FILE="${OUT_DIR}/library_${DATA_CYCLE}.db";
if [ ! -f "${OUT_FILE}.gz" ]; then
    echo "Running load_library.pl ${OUT_FILE}"
    ./load_library.pl ${OUT_FILE};
    gzip ${OUT_FILE};
    echo "--";
fi

echo "Syncing data files with Google Storage:"
gsutil -m rsync -r -d ${OUT_DIR} ${GS_DATA_URL}
gsutil -m acl -r ch -u Allusers:R ${GS_DATA_URL} 2>&1 | grep -v "No changes"

echo "Syncing library files with Google Storage:"
gsutil -m rsync -d -r ${LIBRARY_DIR} ${GS_LIBRARY_URL}
gsutil -m acl -r ch -u Allusers:R ${GS_LIBRARY_URL} 2>&1 | grep -v "No changes"

